travis:
  secure:
    BINSTAR_TOKEN: LjxiiLoeE7iBpZUgTLq7W6mvJje5nO1mqUu3v6sANTfnNlpQxJ0K3sRPMhQCZ8BYWN0XNz9CY+VTJECRPOGn0AYjCiyc/fHugZQOJcmCBGrlR5cVRr52JsUaZyrrmoJBF/a5MOU5ggoNYDfIS7ww7GwX7fCwirDtZwJK+pNLEleiOhSTvKF+KXxD5enPM1W06EiY0t6d6xp1iKHOnbsrdoJ5GW6gfdwgM7zugXq0DX05e+gUQsJ215PoiTJr7GasWBM4PCPHXSr5CVz9QruT7rRgA6Q4Bie5jFlo68WverAvKruXEJOo51As8KTNJDbEzZVWJCwdYl/8SAq3lAmndJWh2Klb+YnZip2+vVrgA6xEcFVmrDoW6Wkqaqqyu4THvW0EIQkEY7w8iyR7JOrRihzPt7PmmbPjUKichbWgbgbmdAkY9rS1bxhpLWScK/hD5oZSJqBOjI3NhPHrAVskkuLRmPVQXST91QSVHqtXA+CVZ3Th/R1pA992cTYKC8lqkUva53R3QwiivINMJj83ewn9PczTEeUfv15E57YuAAR5RUYeDvvxlHZsVPh2wfJ8ToS3egLIj8zlOtHDZkECk1W/E+m5RBZQ75SmKEsC7VnyOMNH7TPEoqohx3aCQEh7zLVll6aiVDASC8rnf5LuaBoq3hpbIZWS9SLXTdE0JSY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
